### ISSUE TITLE
Access to modelDescription file is not guaranteed

### ISSUE THREAD

**Issue by CThuleHansen** [INTO-CPS-Association/unifmu#33]
The assumption in https://github.com/INTO-CPS-Association/unifmu/blob/master/tool/unifmu/resources/backends/python/backend_grpc.py#L197 is that the `modelDescription.xml` is available in the parent folder of the resources folder.
This assumption is local to unifmu and not in the FMI standard.

Therefore, this assumption should be stated explicitly.

**Comment by clegaard** [comment]
The value "value reference to attributes" mapping is no established by the binary, which will attempt to locate and parse the model description during fmi2Instantiate.

If located it will populate the 'UNIFMU_REFS_TO_ATTR" environment variable as described in the README.md
