### ISSUE TITLE
FMU in Model Exchange standard 

### ISSUE THREAD

**Issue by LGentilePL** [INTO-CPS-Association/unifmu#36]
Is it possible to generate FMUs in Model exchange standard through unifmu?

**Comment by clegaard** [comment]
I recently added defined the message types corresponding to the model exchange functionality.
If there is interest in ME functionality, it should be relatively straightforward to introduce the functionality :)

**Comment by clegaard** [comment]
cosimulation (CS) and model exchange (ME) are two fundamentally different ways of using FMUs.
In a nutshell:
* cosim: the numerical solver resides inside the FMU implementation, i.e. when you invoke fmi2DoStep it is the FMUs responsibility to update its outputs.
* model exchange: the FMU provides derivatives, the importing tool does the numerical integration.

I have only ever used FMUs that implement the cosim part of FMI and it is my impression that it is the most commonly used type of FMU.
Are there any specific features you need from ME?

**Comment by LGentilePL** [comment]
I am going to embed the model into the Modelica framework. At the moment, only CS FMUs 1.0 are supported but still not trivial to integrate. Contrarily, embedding ME 1.0 or 2.0 should be much easier.

**Comment by clegaard** [comment]
It seems that you are right:
https://openmodelica.org/doc/OpenModelicaUsersGuide/v1.11.0/fmi.html#fmi-import

I am open to implementing support, however, I can't allocate time for implementing it at the moment.
From the top of my head adding support would look something like:
- [ ] define messages corresponding to FMI2 ME api in protobuf schema
- [ ] add ME C-api in unifmu binary
- [ ] extend existing python and C# backends to accept new messages
- [ ] Write test code for ME FMUs

If you are interested in helping, a good starting point would be an example of ME FMU written in python.

**Comment by clagms** [comment]
Hi @LGentilePL . I hope its ok with you that we close this. For the moment we do not have the capability to support ME. We're trying to get support for FMI 3.0 out asap though. Hope that's ok!
