### ISSUE TITLE
fmu fails when used by other tools

### ISSUE THREAD

**Issue by LGentilePL** [INTO-CPS-Association/unifmu#40]
Hi, both this [FMU checker](https://fmu-check.herokuapp.com/) and the [PyFMI](https://jmodelica.org/pyfmi/index.html#) tool fail when loading the fmu generated with the command`./unifmu generate python testFMU `. 

Error returned by FMU checker
`Failed to read model description. "There is no item named 'modelDescription.xml' in the archive"`

Error returned by PyFMI
`FMIL: module = b'FMIXML', log level = 1: b"Cannot open file '/tmp/JModelica.org/jm_tmps5ubwhd6/modelDescription.xml' for parsing"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyfmi/fmi.pyx", line 8618, in pyfmi.fmi.load_fmu
pyfmi.fmi.InvalidVersionException: The FMU could not be loaded. The FMU version could not be determined. Cannot open file '/tmp/JModelica.org/jm_tmps5ubwhd6/modelDescription.xml' for parsing`

**Comment by clegaard** [comment]
I have only tested the code on windows and linux.
The output of the FMU checker looks like:
```
[INFO][FMUCHK] No input data provided. In case of simulation initial values from FMU will be used.
[INFO][FMUCHK] Printing output file header
"time","real_c","integer_c","boolean_c","string_c"
[INFO][FMUCHK] Model identifier for CoSimulation: unifmu
[INFO][FMILIB] Loading 'linux64' binary with 'default' platform types
[INFO][FMUCHK] Version returned from CS FMU:   2.0
the 'modelDescription.xml' was succefully parsed and it's results used to populate 'UNIFMU_REFS_TO_ATTRS'
INFO:/tmp/fmucktmpWi3K52/resources/backend.py:dispatcher endpoint received: tcp://127.0.0.1:41297
Received handshake
[INFO][FMUCHK] Initialized FMU for simulation starting at time 0
0.0000000000000000E+00,0.0000000000000000E+00,0,0,""
2.0000000000000000E-03,0.0000000000000000E+00,0,0,""
```
Please check that the archive contains the modelDescription.xml in the root.
A common mistake is to zip the outermost folder and not the contents of the folder :)

**Comment by LGentilePL** [comment]
Sure. I was zipping the outermost folder🤦🏻‍♂️. Thank you for the help

**Comment by clegaard** [comment]
No problem ;)
