### ISSUE TITLE
Java assets were deleted

### ISSUE THREAD

**Issue by rudi** [INTO-CPS-Association/unifmu#45]
Hi, I was trying to report some issues with the Java FMU generated code produced by version 0.0.5, but it seems commit 5992c34fac99e8d55b7be8c02e392d46198e4617 deleted them.

**Comment by clegaard** [comment]
Hi Rudi, thanks for raising the issue.
There has been a significant number of changes that have broken support for MATLAB and Java.
* cli refactored from python to Rust
* major changes to serialization
* changes to how valueReferences are mapped to attribute names.
As such they do not appear on the list of supported languages atm.

Reimplementing the Java functionality should be similar to the effort put into the C# code ~ 400 lines of code.
In case Java support would be useful to you I am open to put in some time to reintroduce it ;)

**Comment by rudi** [comment]
Hi, thanks for the answer!  Java support would be great to have for us.  If you restore the files, I can help with testing and documentation, probably also with implementation.

**Comment by clegaard** [comment]
Sounds great. I created a new branch called `java` where I added some placeholder for the Java files.
Previously I used the maven build system, but it felt a bit cumbersome. This time I used gradle.
Do you have any strong preferences?

**Comment by rudi** [comment]
I use gradle in another project, so prefer gradle as well.

**Comment by clegaard** [comment]
I just created a new release which provides a Java backend.
You should be able to create an FMU like:
``` bash
unifmu generate java my_java_fmu
```
In case of problems, please submit a ticket :)

**Comment by rudi** [comment]
Many thanks! I'm at home with an ARM computer right now, will test on Friday when I'm back at an Intel machine.
