### ISSUE TITLE
Understanding the compile mechanism

### ISSUE THREAD

**Issue by ovenygren** [INTO-CPS-Association/unifmu#48]
Recently found this and it is a very interesting approach! Especially for one being new to the FMU concept altogether.

- Using the tool I created a test FMU for C#. I noticed that when validating, the C# projects is built/compiled but only the debug part is available in the resource (<model>\resources\bin\Debug) but no Release part. Is the Release part used if it is available?
- Does the unifmu.dll "recompile" the code resources on every execution or when doing "validate" or how does it work?

**Comment by clegaard** [comment]
Glad you find the work interesting!

If you look at the launch.toml file inside the FMU you should see the following:
``` bash
linux = ["dotnet", "run", "backend.cs"]
macos = ["dotnet", "run", "backend.cs"]
windows = ["dotnet", "run", "backend.cs"]
```
You can modify this file to control how the FMU instance is executed. In this case it runs "dotnet run backend.cs" which will trigger a compile if it has not already been built and execute the resulting binary.
If you already compiled your project you can modify the launch.toml to simply execute the binary.

Regarding debug vs release binaries, this is C# specific. I imagine there is a flag you can pass to the `dotnet run` command to have it do a release build.

The compilation step is only necessary for compiled languages such as C#, for an intrepreted language like python the launch.toml simply executes the backend.py using the systems python intrepreter
``` toml
linux = ["python3", "backend.py"]
macos = ["python3", "backend.py"]
windows = ["python", "backend.py"]
```
Hope this helps!
