### ISSUE TITLE
GUI option

### ISSUE THREAD

**Issue by ovenygren** [INTO-CPS-Association/unifmu#49]
is the GUI option still available?

**Comment by clegaard** [comment]
Unfortunately not at the moment. When I initially wrote the CLI in Python I implemented a GUI using wxPython.
I chose to rewrite the CLI in Rust to get rid of dependencies and to be able to ship it as a single binary.
It would be relatively straightforward to implement in something like [egui](https://github.com/emilk/egui), but I simply don't have the capacity right now.

In case you or anyone else is interested it would be a welcome contribution and one that does not require you to deal with any of the FMI API stuff.

Hope this helps!

**Comment by clagms** [comment]
Closing this as not planned. We don't have the resources at the moment for this. Instead, we are happy to improve the documentation and examples to show how to use the tool better. That's more sustainable than increasing the dependencies of the tool. Hope you understand!
