### ISSUE TITLE
Updating FMU interfaces

### ISSUE THREAD

**Issue by mortenhaahr** [INTO-CPS-Association/unifmu#59]
Thank you for creating such a great tool. I can see myself using this in many cases.

I have a question that might seem a bit trivial but I think other users might have the same question.

What is the "correct" way of updating the interfaces on the FMU?
I have generated my FMU with the command `unifmu generate python anomaly_detection` and tested that it works as intended.
However, I want to change the names of the signals and I don't all 12 of them. (I need two input reals and one output bool).

What would be the preferred way of doing this? Does the tool facilitate any way of doing it automatically?

Edit: I discovered if it is possible to edit the XML file manually. I am still curious if this is the "right way" of doing it

**Comment by Daniella1** [comment]
I'm assuming when you write interfaces, you mean the variables in the modelDescription.xml file.
If so, then these represent the exposed variables of the FMU, and must be updated for each FMU. The FMU that gets generated by unifmu, is just an example of an FMU that can add different types of variables. Then we expect the users to update the model.py file and the modelDescription.xml with the variables that should be exposed in the FMU.
You can use the example FMU that gets generated using unifmu to see how the different types and input/output variables should be defined.

You can find an example FMU of a robot controller, where the [model.py](https://github.com/Daniella1/robot_unifmu/blob/master/robot_controller/resources/robot_controller.py) contains the controller functionality, and the FMU variables are updated in the [modelDescription.xml file](https://github.com/Daniella1/robot_unifmu/blob/master/robot_controller/modelDescription.xml). So the variables in the modelDescription.xml file reflect the variables of the model that we want to expose in the FMU.

Let me know if you have further questions, or if the answer is not clear :)
