### ISSUE TITLE
not able to run the FMU in the simulink

### ISSUE THREAD

**Issue by ankur-cfc** [INTO-CPS-Association/unifmu#61]
I have generated a python based FMU using unifmu. 
This is the simple adder fmu.
The FMU is uploaded on the google drive. Here is the link to it. 
https://drive.google.com/file/d/1Wpvh58X4mx6DPhbvhd39DHQMUInZCHKu/view?usp=drive_link

I am trying to run the simulation after loading this fmu on the simulink. But the simulink crashes after few seconds of running the simulation. It fails to generate any log files. At the bottom it says 'initializing' and then after few seconds it crashes. 

I would really appreciate if I can get some help with this. 

![Screenshot from 2024-04-30 13-40-00](https://github.com/INTO-CPS-Association/unifmu/assets/147786535/5be2ddf2-a15e-4dac-843b-272aecb9bde5)
![Screenshot from 2024-04-30 13-39-49](https://github.com/INTO-CPS-Association/unifmu/assets/147786535/d880e1a0-7b87-4373-a5c9-cb9679bf588e)
![Screenshot from 2024-04-30 13-39-44](https://github.com/INTO-CPS-Association/unifmu/assets/147786535/1648a525-f2a9-4330-ba42-3620b3f155b2)
![Screenshot from 2024-04-30 13-39-38](https://github.com/INTO-CPS-Association/unifmu/assets/147786535/708316bf-6e93-4ebb-9467-056ba6f4640a)
![Screenshot from 2024-04-30 13-39-04](https://github.com/INTO-CPS-Association/unifmu/assets/147786535/1467688d-e01e-4fb6-ada4-3fd06ddd194a)

**Comment by clagms** [comment]
Dear, sorry for the delay.
There can be multiple causes to this. Usually it's the command to run the python part that's failing and you might be missing some python package.

See this documentation: https://github.com/INTO-CPS-Association/unifmu/blob/f921f645d420c236464330abef79de5ce76bdf6b/assets/python/fmi3/README.md#implementing-the-model

We are planning work on improving the logging so these errors can be more easily caught.

**Comment by ankur-cfc** [comment]
@clagms 
Thanks for the reply. I really appreciate it.
Yes. Indeed it was a due to a missing python package. I was able to resolve it.
